# -*- coding: utf-8 -*-
"""test_llm_generated_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMH_53jF_sRa226-vRlQkW2GLHdonwv4
"""

import pytest
from cs520_clean import find_max_1, is_prime

# ---- FIND_MAX: target error & unusual inputs ----
def test_find_max_llm_iteration3():
    # Empty list triggers ValueError
    with pytest.raises(ValueError):
        find_max_1([])

    # Very large numbers
    assert find_max_1([10**6, 10**9, 10**3]) == 10**9

    # Mixed positive/negative
    assert find_max_1([-50, 0, 25, -10]) == 25

    # Duplicate max values
    assert find_max_1([7, 7, 7]) == 7


# ---- IS_PRIME: target rare branches ----
def test_is_prime_llm_iteration3():
    # Negative numbers
    assert not is_prime(-11)

    # Zero
    assert not is_prime(0)

    # Composite near boundary
    assert not is_prime(9)

    # Large prime
    assert is_prime(97)

    # Large composite (product of two primes)
    assert not is_prime(221)