# -*- coding: utf-8 -*-
"""test_llm_generated_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXyGRQaoYzpiejd-hHqBV8UamuHjem35
"""

# test_llm_generated_5.py
from cs520_inclass import reverse_string, factorial, are_anagrams, count_vowels, gcd, even_or_odd, square
import pytest

def test_reverse_string_cases():
    assert reverse_string("abc") == "cba"
    assert reverse_string("") == ""
    assert reverse_string("a") == "a"
    assert reverse_string("123 456") == "654 321"


def test_factorial_cases():
    assert factorial(0) == 1
    assert factorial(1) == 1
    assert factorial(5) == 120
    with pytest.raises(ValueError):
        factorial(-3)

def test_are_anagrams_cases():
    assert are_anagrams("listen", "silent")
    assert are_anagrams("Dormitory", "Dirty room")
    assert not are_anagrams("hello", "world")
    assert are_anagrams("", "")

def test_count_vowels_cases():
    assert count_vowels("Hello") == 2
    assert count_vowels("rhythm") == 0
    assert count_vowels("AEIOU") == 5
    assert count_vowels("") == 0

def test_gcd_cases():
    assert gcd(48, 18) == 6
    assert gcd(0, 5) == 5
    assert gcd(7, 7) == 7
    assert gcd(270, 192) == 6
    assert gcd(-48, 18) == 6

def test_even_or_odd_cases():
    assert even_or_odd(0) == "Even"
    assert even_or_odd(1) == "Odd"
    assert even_or_odd(-2) == "Even"
    assert even_or_odd(-3) == "Odd"

def test_square_cases():
    assert square(5) == 25
    assert square(0) == 0
    assert square(-3) == 9
    assert square(10) == 100

# Extra edge cases for uncovered lines

def test_reverse_string_edge():
    # Handles numbers as string
    assert reverse_string("12345") == "54321"
    # Handles empty string
    assert reverse_string("") == ""
    # Handles mixed cases
    assert reverse_string("AbC") == "CbA"
    # (If applicable) handles non-string inputs gracefully
    with pytest.raises(TypeError):
        reverse_string(None)

def test_factorial_edge():
    # Test negative numbers for ValueError
    with pytest.raises(ValueError):
        factorial(-1)
    # Test float input handling (if code rounds or errors)
    with pytest.raises(TypeError):
        factorial(4.5)

def test_are_anagrams_edge():
    # Case-insensitive and with spaces
    assert are_anagrams("Listen", "Silent")
    assert are_anagrams("Dormitory", "Dirty room")
    # Not anagrams with unequal length
    assert not are_anagrams("abcd", "abc")
    # Non-string input (if handled)
    with pytest.raises(TypeError):
        are_anagrams(123, 321)

def test_count_vowels_edge():
    # Mixed case vowels
    assert count_vowels("AaEeIiOoUu") == 10
    # No vowels
    assert count_vowels("rhythm") == 0
    # Non-string input (if handled)
    with pytest.raises(TypeError):
        count_vowels(None)

def test_gcd_edge():
    # Negative numbers
    assert gcd(-8, 12) == 4
    # When one number is zero
    assert gcd(0, 10) == 10
    # When both are zero (depending on implementation)
    with pytest.raises(ValueError):
        gcd(0, 0)
    # a < b swap case
    assert gcd(3, 9) == 3

