# -*- coding: utf-8 -*-
"""test_cs520_inclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNoLW_GHdCR3-tfJdxSwLBfR7ftnz8p-
"""

from google.colab import files
uploaded = files.upload()

!pip install pytest pytest-cov coverage

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_cs520_inclass.py
# from cs520_inclass import *
#

"""## Problem 1
### Tests to check if a string is a palindrome.
"""

from cs520_inclass import is_palindrome

def test_basic_palindromes():
    assert is_palindrome("madam")
    assert is_palindrome("racecar")
    assert is_palindrome("A man a plan a canal Panama")

def test_non_palindromes():
    assert not is_palindrome("hello")
    assert not is_palindrome("Python")

def test_case_and_space_insensitivity():
    assert is_palindrome("No lemon no melon")
    assert is_palindrome("Was it a car or a cat I saw")

def test_single_and_empty_string():
    assert is_palindrome("a")
    assert is_palindrome("")   # empty string is technically palindrome

def test_punctuation_handling():
    # Depending on your implementation, punctuation may break symmetry.
    # Include both expected True/False to see coverage behavior.
    assert not is_palindrome("Madam, I'm Adam")

"""## Problem 2

### Tests to see if a number is prime
"""

from cs520_inclass import is_prime

def test_small_primes_and_composites():
    assert not is_prime(0)
    assert not is_prime(1)
    assert is_prime(2)
    assert is_prime(3)
    assert not is_prime(4)
    assert is_prime(5)

def test_medium_primes():
    assert is_prime(7)
    assert is_prime(11)
    assert is_prime(13)
    assert not is_prime(15)
    assert not is_prime(21)

def test_large_numbers():
    assert is_prime(97)
    assert not is_prime(100)

def test_negative_numbers():
    assert not is_prime(-3)
    assert not is_prime(-11)

def test_even_and_multiple_of_three():
    assert not is_prime(6)
    assert not is_prime(9)
    assert not is_prime(12)

def test_is_prime_llm_iteration1():
    assert not is_prime(-5)
    assert not is_prime(0)
    assert not is_prime(1)
    assert is_prime(2)
    assert is_prime(3)
    assert not is_prime(100)
    assert not is_prime(49)

"""## Problem 3

### Tests to compute the factorial of a non-negative integer
"""

from cs520_inclass import factorial
import pytest

def test_factorial_basic():
    assert factorial(0) == 1
    assert factorial(1) == 1
    assert factorial(5) == 120

def test_factorial_large():
    assert factorial(10) == 3628800
    assert factorial(7) == 5040

def test_factorial_negative():
    with pytest.raises(ValueError):
        factorial(-1)
    with pytest.raises(ValueError):
        factorial(-5)

"""## Problem 4

### Tests to reverse a given string
"""

from cs520_inclass import reverse_string

def test_reverse_basic():
    assert reverse_string("abc") == "cba"
    assert reverse_string("hello") == "olleh"

def test_reverse_palindrome():
    assert reverse_string("madam") == "madam"  # same both ways

def test_reverse_case_and_space():
    assert reverse_string("A man a plan") == "nalp a nam A"

def test_reverse_empty():
    assert reverse_string("") == ""

"""## Problem 5

### Tests to find the maximum element in a list of integers.
"""

from cs520_inclass import find_max
import pytest

def test_find_max_positive_numbers():
    assert find_max([1, 2, 3, 4, 5]) == 5

def test_find_max_mixed_numbers():
    assert find_max([-10, 0, 10]) == 10
    assert find_max([-5, -1, -9, -2]) == -1

def test_find_max_all_negative():
    assert find_max([-3, -7, -2, -8]) == -2

def test_find_max_single_element():
    assert find_max([100]) == 100

def test_find_max_empty_list():
    with pytest.raises(ValueError):
        find_max([])

"""## Problem 6

### Test to check whether two strings are anagrams.
"""

from cs520_inclass import are_anagrams

def test_simple_anagrams():
    assert are_anagrams("listen", "silent")
    assert are_anagrams("evil", "vile")
    assert are_anagrams("dusty", "study")

def test_anagrams_with_spaces_and_case():
    assert are_anagrams("Dormitory", "dirty room")
    assert are_anagrams("Conversation", "Voices rant on")

def test_not_anagrams():
    assert not are_anagrams("hello", "world")
    assert not are_anagrams("python", "java")

def test_empty_strings():
    assert are_anagrams("", "")

def test_partial_overlap():
    assert not are_anagrams("abc", "ab")

"""## Problem 7

### Tests to count the number of vowels in a string
"""

from cs520_inclass import count_vowels

def test_count_vowels_basic():
    assert count_vowels("hello") == 2
    assert count_vowels("world") == 1

def test_count_vowels_case_insensitive():
    assert count_vowels("AEIOU") == 5
    assert count_vowels("Umbrella") == 3

def test_count_vowels_no_vowels():
    assert count_vowels("rhythm") == 0

def test_count_vowels_empty_string():
    assert count_vowels("") == 0

"""## Problem 8

### Tests to compute the GCD of 2 integers
"""

from cs520_inclass import gcd

def test_gcd_basic_pairs():
    assert gcd(20, 8) == 4
    assert gcd(7, 3) == 1
    assert gcd(100, 10) == 10

def test_gcd_equal_numbers():
    assert gcd(9, 9) == 9
    assert gcd(5, 5) == 5

def test_gcd_with_zero():
    assert gcd(0, 5) == 5
    assert gcd(5, 0) == 5

def test_gcd_negative_numbers():
    assert gcd(-20, 8) == 4
    assert gcd(20, -8) == 4

"""## Problem 9

### Tests to compute if an integer is odd or even
"""

from cs520_inclass import even_or_odd

def test_even_numbers():
    assert even_or_odd(2) == "Even"
    assert even_or_odd(0) == "Even"
    assert even_or_odd(-4) == "Even"

def test_odd_numbers():
    assert even_or_odd(1) == "Odd"
    assert even_or_odd(7) == "Odd"
    assert even_or_odd(-5) == "Odd"

"""## Problem 10

### Tests to return the square of an integer
"""

from cs520_inclass import square

def test_square_basic():
    assert square(2) == 4
    assert square(5) == 25

def test_square_zero():
    assert square(0) == 0

def test_square_negative():
    assert square(-3) == 9
    assert square(-10) == 100

!pytest --cov=cs520_inclass --cov-report=term

!coverage run -m pytest
!coverage report -m --branch

"""## PART-2: REVISED PROMPTS (is_palindrome & is_prime)

### Revised Prompt 1:

#### is_palindrome: Write additional Python unit tests for the function is_palindrome(s) that specifically test branch cases where spaces, punctuation, and capitalization might break symmetry.

#### is_prime: Write additional Python unit tests for the function is_prime(n) that cover untested branches for negative numbers, zero, and small boundary values. Include values such as −5, 0, 1, 2, 3, and large composite numbers.
"""

!pytest test_cs520_inclass.py test_llm_generated_1.py test_llm_generated_2.py test_llm_generated_3.py test_llm_generated_4.py test_llm_generated_5.py \
--cov=cs520_inclass --cov-report=term-missing --disable-warnings -v

"""### Revised Prompt 2:

#### is_palindrome: Generate additional unit tests for the function is_palindrome(s: str) that focus on tricky or rarely covered inputs.Include: numeric palindromes (e.g., ‘12321’), empty strings, whitespace-only inputs, strings with punctuation and symbols, and mixed alphanumeric cases.

#### is_prime: Generate new and challenging unit tests for the function is_prime(n: int). Include negative numbers, 0, 1, large primes (e.g., 97), large composites (e.g., 100), even numbers, and edge cases that might reveal missing branches.
"""

!pytest test_cs520_inclass.py test_llm_generated_1.py test_llm_generated_2.py test_llm_generated_3.py test_llm_generated_4.py test_llm_generated_5.py \
--cov=cs520_inclass --cov-report=term-missing --disable-warnings -v

"""### REVISED PROMPT 3:

#### is_palindrome: Refine the palindrome detection function to achieve full test coverage and handle all realistic input variations, including mixed case, spacing, punctuation, numbers, and special characters.

#### is_prime: Generate additional Python pytest unit tests for the function is_prime(n) to improve branch coverage. The function checks whether an integer is prime. Please include cases for negative numbers, 0, 1, even numbers, large primes, and edge cases that might trigger early returns or missed branches.
"""

!pytest test_cs520_inclass.py test_llm_generated_1.py test_llm_generated_2.py test_llm_generated_3.py test_llm_generated_4.py test_llm_generated_5.py \
--cov=cs520_inclass --cov-report=term-missing --disable-warnings -v

"""## PART-3: FAULT DETECTION CHECK

### For is_palindrome, I introduced a seeded bug where i removed the .lower normalization.

### For is_prime, I introduced a seeded bug where I changed the loop condition to while i * i < n, skipping edge cases like perfect squares
"""

!pytest test_cs520_inclass.py test_llm_generated_1.py test_llm_generated_2.py test_llm_generated_3.py test_llm_generated_4.py test_llm_generated_5.py \
--cov=cs520_inclass --cov-report=term-missing --disable-warnings -v