# -*- coding: utf-8 -*-
"""test_llm_generated_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMH_53jF_sRa226-vRlQkW2GLHdonwv4
"""

from cs520_inclass import is_prime

def test_is_prime_full_branch():
    # --- Branch 1: n <= 1 ---
    assert is_prime(-5) is False
    assert is_prime(0) is False
    assert is_prime(1) is False

    # --- Branch 2: n <= 3 ---
    assert is_prime(2) is True
    assert is_prime(3) is True

    # --- Branch 3: multiples of 2 or 3 ---
    assert is_prime(4) is False   # multiple of 2
    assert is_prime(9) is False   # multiple of 3
    assert is_prime(15) is False  # both multiple of 3 and 5

    # --- Branch 4: numbers checked in while loop ---
    assert is_prime(5) is True    # passes loop start
    assert is_prime(11) is True
    assert is_prime(25) is False  # caught by i*i <= n condition
    assert is_prime(29) is True   # prime just beyond square of 5
    assert is_prime(49) is False  # multiple of 7