# -*- coding: utf-8 -*-
"""test_llm_generated_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGdqUq24ytky6elfdE9_CZ_xnqkOVHS-
"""

from cs520_clean import is_prime



# -------- IS_PRIME TESTS (Iteration 2) --------
def test_is_prime_llm_iteration2():
    # Smallest non-prime
    assert not is_prime(1)

    # Smallest prime
    assert is_prime(2)

    # Even number > 2
    assert not is_prime(10)

    # Prime near square boundary
    assert is_prime(17)

    # Large composite (odd)
    assert not is_prime(81)

    # Edge: negative number
    assert not is_prime(-7)


import pytest
from cs520_inclass import is_prime_2

def test_is_prime_2_branches():
    # Invalid type
    with pytest.raises(TypeError):
        is_prime_2(3.5)

    # n < 2
    assert not is_prime_2(-5)
    assert not is_prime_2(0)
    assert not is_prime_2(1)

    # n <= 3
    assert is_prime_2(2)
    assert is_prime_2(3)

    # divisible by 2 or 3
    assert not is_prime_2(4)
    assert not is_prime_2(9)

    # Prime numbers through the while loop
    assert is_prime_2(5)
    assert is_prime_2(7)
    assert is_prime_2(11)
    assert is_prime_2(13)
    assert is_prime_2(29)

    # Non-prime caught in while loop
    assert not is_prime_2(25)
    assert not is_prime_2(35)



from cs520_inclass import is_prime_3

def test_is_prime_3_all_branches():
    # Covers: n <= 1
    assert not is_prime_3(-5)
    assert not is_prime_3(0)
    assert not is_prime_3(1)

    # Covers: n <= 3
    assert is_prime_3(2)
    assert is_prime_3(3)

    # Covers: n % 2 == 0 or n % 3 == 0
    assert not is_prime_3(4)
    assert not is_prime_3(9)
    assert not is_prime_3(12)
    
    # Covers: while loop condition (i*i <= n) and inside branches
    assert is_prime_3(5)   # passes loop without returning False
    assert is_prime_3(7)
    assert not is_prime_3(25)  # triggers "return False" inside loop
    assert not is_prime_3(35)
    assert is_prime_3(29)  # prime that exits loop via top condition

    # Edge test near square limit
    assert not is_prime_3(49)  # 7*7 triggers while loop boundary



import pytest
from cs520_inclass import is_prime_4


# Test cases
test_cases = [
    (-5, False, "Negative numbers are not prime"),
    (0, False, "Zero is not prime"),
    (1, False, "One is not prime by definition"),
    (2, True, "Two is the smallest prime"),
    (3, True, "Three is prime"),
    (4, False, "Four is composite (2 * 2)"),
    (17, True, "Seventeen is prime"),
    (100, False, "One hundred is composite"),
    (97, True, "Ninety-seven is prime"),
    (121, False, "One hundred twenty-one is composite (11 * 11)"),
]

print("Testing is_prime function:\n")
all_passed = True

for num, expected, description in test_cases:
    result = is_prime(num)
    status = "✓ PASS" if result == expected else "✗ FAIL"
    if result != expected:
        all_passed = False
    print(f"{status}: is_prime({num:4d}) = {result:5} (expected {expected:5}) - {description}")

print(f"\n{'All tests passed!' if all_passed else 'Some tests failed.'}")


def test_is_prime_4_full_branch():
    # Run through all test cases and check expected results
    for n, expected, note in test_cases:
        result = is_prime_4(n)
        assert result == expected, f"Failed for {n}: {note}"

    # Extra branch tests:
    # Non-integer input (for TypeError branch)
    with pytest.raises(TypeError):
        is_prime_4(3.5)
    with pytest.raises(TypeError):
        is_prime_4("17")

    # Force while-loop execution (odd primes/composites)
    assert is_prime_4(5)     # goes through loop, remains prime
    assert not is_prime_4(25)  # fails inside loop
    assert is_prime_4(29)    # passes loop upper limit
